### ISSUE TITLE
How to handle data providers wanting to swissdata-ify their data? 

### ISSUE THREAD

**Issue by mbannert** [swissdata/demo#1]
@christophsax : What if we convince people to go swissdata? How can we make the transition for them as easy as possible? Is it rather scrape them and give them their own data as swissdata set + the script to reproduce it (in case they even use R). What other approaches do we have? 

Simply say they should contact us if they need help? (Could also be a good way for the time being)

**Comment by christophsax** [comment]
And solved for now.
