### ISSUE TITLE
Other data: How to tackle meta information that is rather properties?

### ISSUE THREAD

**Issue by mbannert** [swissdata/demo#2]
We've run into object property type of meta information which is not easily displayed in our key based format. We were looking at time series of parking occupation in ZH. Meta information included `lat`, `long` and several other properties not all of which can be aggregated or a time variant. How do we tackle a set of properties as opposed to dimensions. Seems even more relevant for non-time series data. @christophsax

**Comment by christophsax** [comment]
Let's have some discussions with others and reopen at a later stage.
